### ISSUE TITLE
Do not publish global.json as part of the content

### ISSUE THREAD

**Issue by ransagy** [sotsera/sotsera.blazor.toaster#12]
I've recently started using this library in my blazor app. One change i decided on was removing my global.json file and pinning to the latest SDK available. When i deleted it i noticed the project still locates and uses the global.json file in `.nuget\packages\sotsera.blazor.toaster\0.5.2\contentFiles\any\netstandard2.0\global.json` instead.

Please consider not publishing it as part of the NuGet package to allow users to decide their own SDK version.

**Comment by ghidello** [comment]
Ciao Ran,
sorry for that, I didn't realize that it was going to be bundled with the library. I'll try to have a new version out later today.

Thanks for pointing that out!

**Comment by ransagy** [comment]
Seems like that's the default for the component library template, Maybe we should open an issue in Blazor's repo to change that.

**Comment by ghidello** [comment]
I just pushed a new version (0.5.3) without the global.json files. 
I tried to created a new bloazorlib project but it didn't contain the file so I looked into the toaster history and found a commit where I manually added the global.json file so I'm the one to be blamed for it :smile:

**Comment by ransagy** [comment]
Hah. I was sure i saw it included in a new blazorlib project, but maybe I missed something. Either way, thanks for the quick reply and release :)
