### ISSUE TITLE
Add to DI also as scoped

### ISSUE THREAD

**Issue by anddrzejb** [sotsera/sotsera.blazor.toaster#16]
When using server side, the toasts appear on all instances of application event when run parallel on multiple browsers. I suspect it is because it is added as singleton to the services. Can this be configurable to choose either singleton or scoped?

**Comment by ghidello** [comment]
Hi, the last preview release for blazor 0.8.0 contains the service registration as scoped. Can you test it out or do you need the scoped registration on version 0.6.x?

**Comment by anddrzejb** [comment]
I'm not ready yet for 0.8.0, so yes, I would greatly appreciate update of version 0.6.x.

**Comment by ghidello** [comment]
Sure, i’ll push a release on nuget this evening. I’m not sure if it’s ok to use it on server side for the number of timers ticks that release 0.6.x generates for the toast transitions. Version 0.8 has been moved to css animations so the timer calls have been greatly reduced.

**Comment by anddrzejb** [comment]
You are absolutely right and I will move to 0.8, just at this time my plate is full. Thanks!

**Comment by ghidello** [comment]
version 0.6.1 is being indexed on nuget right now

**Comment by ghidello** [comment]
CIao @anddrzejb, have you got a chance to test this version?

**Comment by ghidello** [comment]
Closing for now: feel free to reopen in case you'll still have issues

**Comment by anddrzejb** [comment]
Sorry for so late reply, but took me forever to upgrade to preview4. Anyway, now seems to be working perfectly. Thanks.
