### ISSUE TITLE
A toastcontainer.razor is added to the project

### ISSUE THREAD

**Issue by larshg** [sotsera/sotsera.blazor.toaster#19]
![image](https://user-images.githubusercontent.com/1165340/56761523-d73aeb80-679d-11e9-93ec-2ad4f12689a5.png)

Which gives compiling errors. To reproduce, remove the project dependency and try add the nuget as dependency.

**Comment by ghidello** [comment]
Thanks for reporting this: obviously I've not been smart enough to test the nuget package after these pretty big changes. I just pushed a new package version which does not include the razor files. Can you please test it when you'll have a chance?
Thanks again!

**Comment by larshg** [comment]
Indeed it made it work 👍
