### ISSUE TITLE
TypeLoadException on server side dotnet core preview8

### ISSUE THREAD

**Issue by Gander7** [sotsera/sotsera.blazor.toaster#24]
This is an awesome toast, unfortunately I'm having issues getting it to work via a package :(

dotnet --version -> `3.0.100-preview8-013656`

Followed readme instructions for serverside:
- `dotnet add package Sotsera.Blazor.Toaster`
- Added `<link href="_content/Sotsera.Blazor.Toaster/toastr.min.css" rel="stylesheet" />` to Host
- Added DI to Startup, also added `using using Sotsera.Blazor.Toaster.Core.Models;` to Startup for Defaults
- Added `<ToastContainer />` and using to MainLayout
- Added `[Inject]` to code-behind class of a page
- added `protected void ShowToast()` method to code-behind class with a body of `Toaster.Info("toast body text");`

No Build/Compiler Errors.
Runtime error on run: 
[![Image from Gyazo](https://i.gyazo.com/ae0ab31431c27233cdb2bedcacfd10e8.png)](https://gyazo.com/ae0ab31431c27233cdb2bedcacfd10e8)
[![Image from Gyazo](https://i.gyazo.com/4e1fc0eac1156b09d936eda69d33d836.png)](https://gyazo.com/4e1fc0eac1156b09d936eda69d33d836)

Raw Error: https://pastebin.com/R5D4aubU

I was able to replicate using a new project (`dotnet new blazorserver`).

**Comment by ghidello** [comment]
Hi,
can you please try to install the library using the command
`dotnet add package Sotsera.Blazor.Toaster --version 1.0.0-preview.8.1`?

I must update the installation instructions in the readme because the last library version is considered a **prerelease** and the command you used installs the last available release. Thanks for the heads up.

**Comment by Gander7** [comment]
Works :)
Thanks for the quick reply, this is a great resource.

The only other thing missing from the readme is a mention to add `using using Sotsera.Blazor.Toaster.Core.Models;` to Startup.cs for the Dependency injection configuration portion.

**Comment by ghidello** [comment]
@Gander7 Sorry for the late response. I added the `using` reference to the readme. Thanks for the suggestion!
