### ISSUE TITLE
System.ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by manureini** [sotsera/sotsera.blazor.toaster#30]
Hello ;)

In very rare conditions when switching fast between different pages I get this exception, which
crashes the whole application.

```
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.RemoveAt(Int32 index)
   at System.Collections.Generic.List`1.Remove(T item)
   at Sotsera.Blazor.Toaster.Core.Toaster.Remove(Toast toast)
   at Sotsera.Blazor.Toaster.Core.Toast.TimerElapsed(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.TimerQueueTimer.CallCallback(Boolean isThreadPool)
   at System.Threading.TimerQueueTimer.Fire(Boolean isThreadPool)
   at System.Threading.TimerQueue.FireNextTimers()

```
Maybe it could help you to find an issue.

I can not reproduce it, but it happens..... =(

**Comment by ghidello** [comment]
Thanks for reporting the issue. It looks like a toast timer elapsed after the toast had already been removed. Trying to narrow down the possible scenarios, are you removing the toast when a page is unloaded?
Are you hosting the ToastComponent in the App component or in the template?
It would be helpful to have a sample project simulating your scenario to test out.

**Comment by manureini** [comment]
No, I do not remove the toast via command or something.
I'm just using toast.success() in a component with the dependency injection from blazor.

I'm using the <ToastContainer /> in MainLayout.

I can not provide a sample project sorry. I also can not reproduce it =(
For me it looks like it happens when the toast is shown and you switch the page.

Maybe a fix would be to make the `IList<Toast> Toasts` Threadsafe with a concurrent thing, and
only remove the Toast if it is present in the list. But I can only guess, because I don't know more details.
My guess is that `DisposeToasts` and `Remove(Toast toast)` is maybe called at the same moment.

**Comment by ghidello** [comment]
Sorry for the late answer and thanks for your response. I'll have to look into making the toast list thread safe. Hopefully I'll work on it during the weekend.
Thanks again

**Comment by ghidello** [comment]
I just pushed a new version with some thread safety guards. Can you please check it out and see if the problem still happens?

**Comment by manureini** [comment]
Hello ;)

Thank you very much for your work!
It looks now very good, but I'll test and notify you, if I get the exception again.

lordmampf
