### ISSUE TITLE
Sample projects- Message is above Title

### ISSUE THREAD

**Issue by bholland314** [sotsera/sotsera.blazor.toaster#31]
While evaluating this amazing work, I noticed that in the sample projects, ClientSide and ServerSide, that the Message appeared above the Title. This may be as designed, but it seemed odd to me. It was also odd that removing the title text in the input box causes no toastr to appear.
The cause of this confusion is in both Index.razor files.
void Show(ToastType type)
Toaster.Add(type, title, message, config =>
title and message are in the wrong order.
Looking at the definition for Toaster.Add message is the 2nd parameter and title is the third.
Easy fix is to change the order in the Index.razor files, but maybe you really intended title to be the second parameter. Just a thought.

**Comment by ghidello** [comment]
What a facepalm moment. You’re right on the proposed fix. Now I wonder how long those sample pages have been broken.. thanks for the heads up!
