### ISSUE TITLE
Is there a way to add text-alignment as a configuration item

### ISSUE THREAD

**Issue by bholland314** [sotsera/sotsera.blazor.toaster#32]
For example:
Instead of having to modify the CSS
.toast-title {
    font-weight: bold;
    **text-align: center;**
}
.toast-message {
    -ms-word-wrap: break-word;
    word-wrap: break-word;
    **text-align: center;**
}
Maybe something like
services.AddToaster(config =>
            {
                config.TextAlignment = Defaults.Classes.TextAlignment.Center

Thanks

**Comment by ghidello** [comment]
Yes, we can add some classes for the text alignment and maybe a couple configuration properties so the title and message can be placed independently. Good suggestion, thanks!

**Comment by ghidello** [comment]
I just pushed a new version to the dev branch that adds a couple of properties for configuring the title and message classes so the text position can now be changed using, for example, some bootstrap classes like 
```c#
config.ToastTitleClass = "toast-title text-center";
config.ToastMessageClass = "toast-message text-right";
```

Can you test it out and see if this may be a solution?

**Comment by bholland314** [comment]
Tested and works as expected. Do you mind if I add options in the sample projects?
Thanks,

**Comment by ghidello** [comment]
Sure, please go ahead any help is ver much appreciated! Thanks

**Comment by bholland314** [comment]
Replied to the wrong thread.
Ok, I will make a new branch and PR it prob today.

I also figured out how to do HTML in the Title and Message. It's built into
Toastr. I will create another branch and PR to add the escapeHtml option.

**Comment by bholland314** [comment]
Can you add me as a collaborator?
bholland314

Thanks,
Brian
