### ISSUE TITLE
ToastOptions should have field for PositionClass

### ISSUE THREAD

**Issue by bholland314** [sotsera/sotsera.blazor.toaster#33]
Currently there is no way to change the location of the toasts per toast message. The global ToasterConfiguration must be changed, which changes the position for all toasts. We have a special case where the designer would like to control a particular toast messages position. Is this possible?
Thanks

**Comment by ghidello** [comment]
The position class is applied to the toasts container and there is only one of it so, at the moment, what you’re asking is not possible. I would like to revisit the whole library to make the css transitions better so maybe I’ll keep this request in mind at that time

**Comment by bholland314** [comment]
Actually after I thought about it for a few minutes...  I realized that what I was asking for was not really feasible nor really what I need. For some reason I forgot that the toast display is the display of the toasts in the array. Can't have one here and other over there, unless there are 2 toast containers. I was just worried about the user clicking to fast and seeing the new toast show up in the old location. Thanks for the response. I was going to delete this issue anyway.

**Comment by ghidello** [comment]
I'll close it for now then. Feel free to reopen it in case you want to chat about it more.
