### ISSUE TITLE
Overriding #toast-container > div

### ISSUE THREAD

**Issue by bholland314** [sotsera/sotsera.blazor.toaster#34]
What is the best way to override #toast-container > div css properties?
Our designer wants to use the bootstrap alert colors.
In our Startup.cs file I set the configuration to:
services.AddToaster(config =>
            {
                config.PositionClass = Defaults.Classes.Position.TopRight;
                config.IconClasses.Error = "alert-danger";
            }
This changes the background-color to the color specified in bootsrap's alert-danger class, but the color of the text is still what is defined by #toast-container > div (color: #ffffff;) and not what is defined by alert-danger (color: #622938;).

I'm not sure how we are supposed to be changing css properties the blazor way.

Thanks

**Comment by bholland314** [comment]
I ended up solving this by copying toastr.css and adding it to my project and making the changes I needed directly in the file and then changing the link to it from this
<link href="_content/Sotsera.Blazor.Toaster/toastr.min.css" rel="stylesheet" />
to 
<link href="~/_assets/css/toastr.css" rel="stylesheet" />

I hope someday Blazor does Componentized style sheets like angular does. Makes things so neat and  easy to deal with.

**Comment by ghidello** [comment]
You answered while I was writing my best attempt to change the toaster css to match the boostrap colors. :smile: (and I'm a terrible designer so I would be interested in your changes)

**Comment by bholland314** [comment]
I'm not a big fan of the changes, but I'm not a "Designer", I just make things work.. Honestly I like the toastr colors better. Been using those for years.

**Comment by bholland314** [comment]
Ok, I will make a new branch and PR it prob today.

I also figured out how to do HTML in the Title and Message. It's built into
Toastr. I will create another branch and PR to add the escapeHtml option.
