### ISSUE TITLE
Sample projects - Top center and Bottom center don't work as expected

### ISSUE THREAD

**Issue by bholland314** [sotsera/sotsera.blazor.toaster#35]
When running the Sample projects and setting the Position dropdown  to Top center or Bottom center, the toasts appear in the Top left position instead of being in the top center and bottom center of the page as expected. 
I believe this is because the toastr.css file does not contain toast-top-center or toast-bottom-center classes, however the toastr.min.css file does contain these classes, but they are wrong.
If you add or change these classes to this, we will get centered toasts:
.toast-top-center {
    top: 0px;
    left: 50%;
    margin-right: -50%;
    transform: translate(-50%, 0%)
}

.toast-bottom-center {
    bottom: 0px;
    left: 50%;
    margin-right: -50%;
    transform: translate(-50%, 0%)
}

**Comment by ghidello** [comment]
I just tested the sample [project](https://blazor-toaster.sotsera.com) and the top-center and bottom-center options are both working for me on chrome and firefox so I probably didn't understand your problem: It's too late for me to be doing this! :smile: I'll have to look into it hopefully during the weekend.

**Comment by bholland314** [comment]
I re cloned the project and everything works as expected. I tried to compare my env to the latest, but couldn't find the issue. Somehow I messed something up. Will need to be more careful. Thanks
