### ISSUE TITLE
Question about usage and credit

### ISSUE THREAD

**Issue by Garderoben** [sotsera/sotsera.blazor.toaster#41]
Hello Alessandro,

I been using your toaster for different projects of mine before and think its great. And why reinvent the wheel?

Now we just first released our open source Blazor Component library under MIT license [MudBlazor](https://mudblazor.com/), [GitHub Page](https://github.com/Garderoben/MudBlazor)
I just want to ask for your permission to "borrow" some of your code in our project. We will use it in a modified version as a snackbar, massage/notification type. We would also like to give you proper credit with your name and link to your GitHub if you agree of course.

Thanks in advance!

**Comment by ghidello** [comment]
Hi Jonny,
I'm very glad if this library has been useful even if I neglected if for almost an year.
Anyway, it is licensed under MIT too so feel free to borrow whatever you need: I'll make sure to check your library as soon as I'll be able to work on Blazor again.

Thanks for stopping by.
Ciao!

**Comment by Garderoben** [comment]
> Hi Jonny,
> I'm very glad if this library has been useful even if I neglected if for almost an year.
> Anyway, it is licensed under MIT too so feel free to borrow whatever you need: I'll make sure to check your library as soon as I'll be able to work on Blazor again.
> 
> Thanks for stopping by.
> Ciao!

Awesome thanks, will update live website tomorrow with you name and repo in credits! Thanks.
